#!/usr/bin/env bash
# Apply .do/app.yaml to the live App Platform app, with the secrets merged in from .env.
#
# Why this exists. `doctl apps update --spec` replaces the *whole* spec, and .do/app.yaml declares
# GEMINI_API_KEY and DS_ADMIN_TOKEN as `type: SECRET` with no value - because a value there would be a
# secret committed to git. Applying that file directly therefore sets both secrets to the empty string.
# That is not theoretical: it is how the app was first created, and it left the live site with
# hasKey:false, so every visitor's one free portrait was refused before it was attempted.
#
# So: never `doctl apps update --spec .do/app.yaml`. Run this instead. It reads the real values from
# .env (gitignored), merges them into the spec in memory, and pipes the result to doctl on stdin - the
# merged spec is never written to disk, so there is no temp file to leak or forget to delete.
#
# Usage:  bash deploy/do-apply.sh [APP_ID]
#   APP_ID falls back to $DS_APP_ID, which .env is the natural place for.
#   DS_UPDATE_SOURCES=1 also rebuilds from the git branch; off by default, because an env-only change
#   needs no rebuild (these are RUN_TIME vars) and every deploy wipes runs/.
set -euo pipefail
cd "$(dirname "$0")/.."

SPEC=.do/app.yaml
[ -f "$SPEC" ] || { echo "no $SPEC" >&2; exit 1; }
[ -f .env ] || { echo "no .env - it holds GEMINI_API_KEY and is gitignored on purpose" >&2; exit 1; }

# Read .env without executing it: a stray backtick in a key should not run.
while IFS='=' read -r k v; do
  case "$k" in ''|\#*) continue;; esac
  v="${v%\"}"; v="${v#\"}"; v="${v%\'}"; v="${v#\'}"
  export "$k=$v"
done < .env

APP_ID="${1:-${DS_APP_ID:-}}"
[ -n "$APP_ID" ] || { echo "pass the app id, or set DS_APP_ID in .env" >&2; exit 1; }

: "${GEMINI_API_KEY:?set GEMINI_API_KEY in .env}"

# The board can only be cleared by someone holding this, so it wants to exist and to be stable across
# applies. Generate once, remember it in .env.
if [ -z "${DS_ADMIN_TOKEN:-}" ]; then
  DS_ADMIN_TOKEN=$(openssl rand -hex 24)
  export DS_ADMIN_TOKEN
  printf '\n# generated by deploy/do-apply.sh - unlock the CLEAR control at /?admin=<this>\nDS_ADMIN_TOKEN=%s\n' \
    "$DS_ADMIN_TOKEN" >> .env
  echo "generated a DS_ADMIN_TOKEN and appended it to .env" >&2
fi

# Merge, and report what was filled in by name only - never the value.
merged=$(python3 - "$SPEC" <<'PY'
import os, sys, yaml
spec = yaml.safe_load(open(sys.argv[1]))
filled = []
for svc in spec.get('services', []):
    for env in svc.get('envs', []):
        if env.get('type') == 'SECRET' and not env.get('value'):
            val = os.environ.get(env['key'], '')
            if val:
                env['value'] = val
                filled.append(env['key'])
            else:
                # Leave it out entirely rather than send an empty secret, which is the bug this
                # script exists to prevent.
                env.pop('value', None)
                print(f"warning: {env['key']} is not in .env; it will stay unset", file=sys.stderr)
print('filled from .env: ' + (', '.join(filled) or '(nothing)'), file=sys.stderr)
print(yaml.safe_dump(spec, sort_keys=False))
PY
)

args=(apps update "$APP_ID" --spec - --format ID,Spec.Name,DefaultIngress,InProgressDeployment.ID)
[ "${DS_UPDATE_SOURCES:-0}" = "1" ] && args+=(--update-sources)
printf '%s' "$merged" | doctl "${args[@]}"

echo
echo "note: App Platform has no persistent storage, so this deploy resets runs/ -"
echo "      the leaderboard, the portraits and everyone's free-portrait credit."
